splash = false
ipc = off

wallpaper {
    monitor = DP-2
    path = ~/.wallpapers/Night_City.png
    fit_mode = cover 
}
wallpaper {
    monitor = DP-1
    path = ~/.wallpapers/purple_gasstation_abstract_dark_night.jpg
    fit_mode = cover 
}
wallpaper {
    monitor = HDMI-A-2
    path = ~/.wallpapers/Dreamy-Aesthetic-Home-Under-Moonlight.png
    fit_mode = cover 
}
